blog/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('', views.blogView, name='blog'),
    path('<slug:slug>/', views.blogSingleView, name='blog_single'),
    path('comment', views.comments,  name='comment'),
    path('search', views.search,  name='search'),
    path('newsletter', views.NewsLetter, name='newsletter')
]

payments/urls.py
from django.urls import path
from . import views

urlpatterns = [
	path('initiate-payment/<int:id>', views.initiate_payment, name='initiate_payment'),
	path('verify-payment/<str:ref>/', views.verify_payment, name='verify_payment'),
]

software/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('software_company.urls')),
    path('blog/', include('blog.urls')),
    path('payments/', include('payments.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.urls import reverse
from tinymce.models import HTMLField  

# Create your models here.
class Categories(models.Model):
    name = models.CharField(max_length=150)

    class Meta:
        verbose_name_plural = "Categories"

    def __str__(self):
        return self.name
    
class Tag(models.Model):
    name = models.CharField(max_length=150)

    def __str__(self):
        return self.name
    


class Blog(models.Model):
    author = models.CharField(max_length=150)
    title = models.CharField(max_length=150)
    slug = models.SlugField(null=False, unique=True)
    thumbnail = models.ImageField(blank=True)
    summary = models.CharField(blank=True, null=True, max_length=600)
    content = HTMLField()
    tags = models.ManyToManyField(Tag, blank=True)
    categories = models.ForeignKey(Categories, blank=True, null=True, on_delete=models.SET_NULL)
    date = models.DateTimeField(auto_now_add=True)
    comments_count = models.IntegerField(null=True, blank=True)
    dateUpdated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("blog_single", kwargs={"slug": self.slug})

    @property
    def imageURL(self):
        try:
            url = self.thumbnail.url
        except:
            url = ''
        return url
    @property
    def comment_count(self):
        try:
            comments_count = self.commnt_set.count()
        except:
            comments_count = 0
        return comments_count
    
class Comment(models.Model):
    name = models.CharField(max_length=150)
    email = models.EmailField(blank=True, null=True)
    message = models.TextField(max_length=1000)
    blog = models.ForeignKey(Blog, blank=True, null=True, on_delete=models.SET_NULL) 
    date = models.DateTimeField(auto_now_add=True)
    validated = models.BooleanField(default=True)
    replyId = models.CharField(max_length=150, blank=True, null=True)

    class Meta:
        ordering = ["-date"]

    def __str__(self):
        return self.name
    

class Newsletter(models.Model):
    email = models.EmailField()

    def __str__(self):
        return self.email

class Social_Links(models.Model):
    name = models.CharField(max_length=100)
    link = models.URLField()

    def __str__(self):
        return self.name

payments/models.py
from django.db import models
import secrets
from software_company.models import CustomerInvoice
from .paystack import Paystack

# # Create your models here.
# class UserWallet(models.Model):
# 	user = models.OneToOneField(User, null=True, on_delete=models.CASCADE)
# 	currency = models.CharField(max_length=50, default='NGN')
# 	balance = models.PositiveIntegerField(default=0)
# 	created_at = models.DateTimeField(default=timezone.now, null=True)

# 	def __str__(self):
# 		return self.user.__str__()

class Payment(models.Model):
	invoice = models.ForeignKey(CustomerInvoice, blank=True, null=True, on_delete=models.SET_NULL )
	amount = models.PositiveIntegerField()
	ref = models.CharField(max_length=200)
	phone_number = models.CharField(max_length=20)
	email = models.EmailField()
	verified = models.BooleanField(default=False)
	date_created = models.DateTimeField(auto_now_add=True)

	class Meta:
		ordering = ('-date_created',)

	def __str__(self):
		return f"Payment: {self.amount}"

	def save(self, *args, **kwargs):
		while not self.ref:
			ref = secrets.token_urlsafe(50)
			object_with_similar_ref = Payment.objects.filter(ref=ref)
			if not object_with_similar_ref:
				self.ref = ref

		super().save(*args, **kwargs)
	
	def amount_value(self):
		return int(self.amount) * 100

	def verify_payment(self):
		paystack = Paystack()
		status, result = paystack.verify_payment(self.ref, self.amount)
		if status:
			if result['amount'] / 100 == self.amount:
				self.verified = True
			self.save()
		if self.verified:
			return True
		return False
	

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.core.paginator import EmptyPage, Paginator
from . models import Blog, Tag, Categories, Comment, Newsletter
from django.db.models import  Q
from django.contrib import messages

# Create your views here.
def blogView(request):
    # infos = Company.objects.order_by('id')[:1]
    # links = Social_Links.objects.all()
    # contacts_infos = Contact_us.objects.order_by('id')[:1]
    blogs = Blog.objects.all().order_by('dateUpdated')
    paginator = Paginator(blogs, 5)
    page = request.GET.get('page')
    paged_blogs = paginator.get_page(page)
    posts = Blog.objects.order_by('-dateUpdated')[:5]
    tags = Tag.objects.all()
    categories = Categories.objects.all()


    # sort_by = request.GET.get('sort', 'l2h')
    # if sort_by == "l2h":
        # blogs = Blog.objects.order_by('-comments_count')
        # for blog in blogs:
        #     print(blog.comments_count)
    
                     
    context = {
        'blogs' :paged_blogs,
        # 'infos' : infos,
        # 'links' : links,
        # 'contacts_infos':contacts_infos,
        'posts' : posts,
        'tags' : tags,
        'categories' : categories
    }
    return render(request, 'blog.html', context)

def search(request):
    # infos = Company.objects.order_by('id')[:1]
    # links = Social_Links.objects.all()
    # contacts_infos = Contact_us.objects.order_by('id')[:1]
    tags = Tag.objects.all()
    categories = Categories.objects.all()
    queryset_list = Blog.objects.order_by('-dateUpdated')
    category_id = request.GET.get('category', 0)
    tag_id = request.GET.get('tag', 0)
    query = request.GET.get('query')
    
    # paginator = Paginator(queryset_list, 2)
    # page = request.GET.get('page')
    # paged_blogs = paginator.get_page(page)
        # Keywords
    
    if query:
        queryset_list = queryset_list.filter(Q(content__icontains=query)| Q(title__icontains=query))
   
    if category_id :
        queryset_list = queryset_list.filter(categories__id=category_id )
    if tag_id :
        queryset_list = queryset_list.filter(tags__id=tag_id )
    
    context ={
        # 'infos' : infos,
        # 'links' : links,
        # 'contacts_infos':contacts_infos,
        'blogs': queryset_list,
        'tags' : tags,
        'categories' : categories,
        "category_id" : int(category_id)
    }
    return render(request, 'search.html', context)

def blogSingleView(request, slug):
    blog = get_object_or_404(Blog, slug=slug)
    blogs = Blog.objects.filter(categories = blog.categories).exclude(id = blog.id)[:5]#reltaed blogs
    tags = Tag.objects.filter(blog__id = blog.id)
    
    comments = blog.comment_set.all()
    context = {
        'blog': blog,
        'blogs' : blogs,
        'comments' : comments,
        'tags' : tags
    }
    return render(request, 'blog-single.html', context)


def comments(request):
    if request.method == 'POST':
        blog_id = request.POST['blog']
        blog = get_object_or_404(Blog, id=blog_id)
        name = request.POST['name']
        email = request.POST['email']
        message = request.POST['comment']

        comment = Comment(name=name, blog = blog, email=email, message=message)
        comment.save()
        messages.success(request, 'comment published successfuly!!')
        return redirect('https://blog.salesflowpro.xyz/blog/' + blog.slug  + '#comment' )

def NewsLetter(request):
    if request.method == 'POST':
        email = request.POST['email']

        newsletter = Newsletter(email=email)
        newsletter.save()
        messages.success(request, 'thanks for subscribing to our newsletter!')
        return redirect('blog')

payments/views.py
from django.shortcuts import render, HttpResponsePermanentRedirect, redirect
from django.contrib import messages
from datetime import date
from django.contrib.auth.decorators import login_required
from .models import Payment
from software_company.models import CustomerInvoice, CompanyInfor
from django.conf import settings

def initiate_payment(request, id):
	invoice = CustomerInvoice.objects.filter(id=id).first()
	companyinfor = CompanyInfor.objects.order_by('id')[:1]

	tax = ((16 * invoice.amount)/100)
	discount = ((16 * invoice.amount)/100)

	total = invoice.amount + tax - discount

	if request.method == "POST":
		invoice_id = request.POST['invoice']

		pk = settings.PAYSTACK_PUBLIC_KEY
		invoice = CustomerInvoice.objects.filter(id=invoice_id).first()
		tax = ((16 * invoice.amount)/100)

		discount = ((16 * invoice.amount)/100)

		total = invoice.amount + tax - discount
		phone_number=invoice.customer_plan.customer.phone_number
		email = invoice.customer_plan.customer.email
		payment = Payment.objects.create(amount=total, phone_number=phone_number, email=email, invoice=invoice)
		payment.save()

		context = {
			'payment': payment,
			'field_values': request.POST,
			'paystack_pub_key': pk,
			'companyinfor': companyinfor,
			'amount_value': payment.amount_value(),
		}
		return render(request, 'make-payment.html', context)
	context = {
			'invoice': invoice,
			'companyinfor': companyinfor,
			'tax': tax,
			'total': total
		}
	return render(request, 'payment.html', context)


def verify_payment(request, ref):
	payment = Payment.objects.get(ref=ref)
	verified = payment.verify_payment()

	if verified:
		payment.invoice.paid = True
		payment.invoice.date_paid = date.today()
		payment.invoice.save()
		messages.success(request, f'Your Payments have been received Succesfully !!!')
		messages.success(request, f'Your account will be ready within 24 hours !!!')
	return redirect("landing_page")

templates/blog-single.html
{% extends 'blog-main.html' %}
{% load static %}
{% block title%} {{blog.title}} {%endblock title%}
{% block meta%} {{blog.summary}} {%endblock meta%}

{% block content %}

  <main id="main">

    <!-- ======= Breadcrumbs ======= -->
    <section class="breadcrumbs">
      <div class="container mt-2">

        <ol>
          <li><a href="{% url 'blog' %}">Blog</a></li>
          <li>Blog Single</li>
        </ol>
        <h1>{{blog.title}}</h1>

      </div>
    </section><!-- End Breadcrumbs -->

    <!-- ======= Blog Single Section ======= -->
    <section id="blog" class="blog">
      <div class="container" data-aos="fade-up">

        <div class="row">
          {% if messages %}
            {% for message in messages %}
              <div class="alert alert-warning alert-dismissible fade show" role="alert">
                {{ message }}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
              </div>


            {% endfor %}
          {% endif %}

          <div class="col-lg-8 entries">

            <article class="entry entry-single">

              <div class="entry-img">
                {% if blog.thumbnail %}
                <img src="{{blog.imageURL}}" class="img-fluid" alt="">
                {% else %}
                <img src="{% static 'assets/img/blog-' %}{{blog.id}}.jpg" style="width: 100%;" class="img-fluid" alt=""/>
                {% endif %}
              </div>

              <!-- <h2 class="entry-title">
                {{blog.title}}
              </h2> -->

              <div class="entry-meta">
                <ul>
                  <li class="d-flex align-items-center"><i class="bi bi-person"></i> {{blog.author}}</li>
                  <li class="d-flex align-items-center"><i class="bi bi-clock"></i><time datetime="2020-01-01">{{ blog.dateUpdated | date}}</time></li>
                  <li class="d-flex align-items-center"><i class="bi bi-chat-dots"></i> <a class="nav-link scrollto" href="{%url 'blog' %}#comment">{{blog.comment_set.count}} Comments</a></li>
                </ul>
              </div>

              <div class="entry-content">
                {{blog.content|safe}}

              </div>

              <div class="entry-footer">
                <i class="bi bi-folder"></i>
                <ul class="cats">
                  
                  <li><a href="{% url 'search' %}?query={{ query }}&category={{blog.categories.id}}" title="category">{{blog.categories.name}}</a></li>
                  
                </ul>

                <i class="bi bi-tags"></i>
                <ul class="tags">
                  {%for tag in tags %}
                  <li><a href="{% url 'search' %}?query={{ query }}&tag={{tag.id}}"  title="tag">{{tag.name}}</a></li>
                  {%endfor%}
                  
                </ul>
              </div>

            </article><!-- End blog entry -->

            <!-- <div class="blog-author d-flex align-items-center">
              <img src="assets/img/blog/blog-author.jpg" class="rounded-circle float-left" alt="">
              <div>
                <h4>Jane Smith</h4>
                <div class="social-links">
                  <a href="https://twitters.com/#"><i class="bi bi-twitter"></i></a>
                  <a href="https://facebook.com/#"><i class="bi bi-facebook"></i></a>
                  <a href="https://instagram.com/#"><i class="biu bi-instagram"></i></a>
                </div>
                <p>
                  Itaque quidem optio quia voluptatibus dolorem dolor. Modi eum sed possimus accusantium. Quas repellat voluptatem officia numquam sint aspernatur voluptas. Esse et accusantium ut unde voluptas.
                </p>
              </div>
            </div>End blog author bio -->

            <div class="blog-comments" id="comment">

              <h4 class="comments-count">{{blog.comment_set.count}} Comments</h4>

              {% for comment in comments %}

              <div id="comment-2" class="comment">
                <div class="d-flex">
                  <div>
                    <h5>{{comment.name}} <a class="scrollto reply" href="{%url 'blog' %}#replys" ><i class="bi bi-reply-fill"></i>Reply</a></h5>
                    <time datetime="2020-01-01">{{comment.date}}</time>
                    <p>{{comment.message}}</p>
                  </div>
                </div>

              </div><!-- End comment #2-->
              {%endfor%}

              <div class="reply-form" id="replys">
                <h4>Leave a Comment</h4>
                <p>Your email address will not be published. Required fields are marked * </p>
                <form method="POST" class=""  id="comment" action="{% url 'comment' %}">
                  {% csrf_token %}
                  <div class="row">
                    <div class="visually-hidden">
                      <label for="blog" class="form-label visually-hidden"> blog </label>
                          <select class="form-select" id="floatingSelect" name='blog'aria-label="State">
                              <option value="{{blog.id}}">blog id</option>
                          </select>
                    </div>
                    <div class="col-md-6 form-group">
                      <input name="name" type="text" class="form-control" placeholder="Your Name*" required>
                    </div>
                    <div class="col-md-6 form-group">
                      <input name="email" type="text" class="form-control" placeholder="Your Email*" required>
                    </div>
                  </div>
                  <div class="row">
                    <div class="col form-group">
                      <input name="website" type="text" class="form-control" placeholder="Your Website">
                    </div>
                  </div>
                  <div class="row">
                    <div class="col form-group">
                      <textarea name="comment" class="form-control" placeholder="Your Comment*" required></textarea>
                    </div>
                  </div>
                  <button type="submit" class="btn justify-content-center btn-primary">Post Comment</button>

                </form>
                

              </div>

            </div><!-- End blog comments -->

          </div><!-- End blog entries list -->

          <div class="col-lg-4">

            <div class="sidebar">

              <h3 class="sidebar-title">Related Posts</h3>
              <div class="sidebar-item recent-posts">
                {% for blog in blogs %}
                <div class="post-item clearfix">
                  {% if blog.thumbnail %}
                  <img src="{{blog.imageURL}}" class="img-fluid" alt="">
                  {% else %}
                  <img src="{% static 'assets/img/blog-' %}{{blog.id}}.jpg" style="width: 100%;" class="img-fluid" alt=""/>
                  {% endif %}
                  <h4><a href="{% url 'blog_single' blog.slug %}">{{blog.title}}</a></h4>
                  <time datetime="2020-01-01">{{ blog.dateUpdated }}</time>
                </div>
                {%endfor%}

              </div><!-- End sidebar recent posts-->

            </div><!-- End sidebar -->

          </div><!-- End blog sidebar -->

        </div>

      </div>
    </section><!-- End Blog Single Section -->

  </main><!-- End #main -->
  

 {% endblock %}

templates/call-to-action.html
{% load static %}

<!-- ======= Call To Action Section ======= -->
{% if callToActions %}
<section id="call-to-action" class="call-to-action">
    <div class="container" data-aos="zoom-out">
      <div class="row justify-content-center">
        <div class="col-lg-8 text-center">
          <h3><a class="get-a-quote" href="{% url 'pricing' %}"><button class="btn btn-primary mt-1">Get Started</button></a></h3>
          <!-- <p>{{ call.message }}</p> -->
          <p>{{callToActions.message }}<span class='align-items-center mb-3'>.</span> </p>
          <!-- <p>{{ call.reminder }}</p> -->
        </div>
      </div>
    </div>
</section><!-- End Call To Action Section -->
{% endif %}

templates/faq.html
{% load static %}

<!-- ======= Frequently Asked Questions Section ======= -->
{% if faqs %}
<section id="faq" class="faq">
    <div class="container" data-aos="fade-up">

      <div class="section-header">
        <span>Frequently Asked Questions</span>
        <h2>Frequently Asked Questions</h2>

      </div>

      <div class="row justify-content-center" data-aos="fade-up" data-aos-delay="200">
        <div class="col-lg-10">

          <div class="accordion accordion-flush" id="faqlist">
            {% for faq in faqs %}
            <div class="accordion-item">
              <h3 class="accordion-header">
                <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#faq-content-{{ faq.id }}">
                  <i class="bi bi-question-circle question-icon"></i>
                  {{ faq.question |safe }}
                </button>
              </h3>
              <div id="faq-content-{{ faq.id }}" class="accordion-collapse collapse" data-bs-parent="#faqlist">
                <div class="accordion-body">
                  {{ faq.answer|safe }}
                </div>
              </div>
            </div><!-- # Faq item-->
            {% endfor %}
          </div>

        </div>
      </div>

    </div>
</section><!-- End Frequently Asked Questions Section -->
{% endif %}

templates/make-payment.html
{% extends 'main.html' %}
{% load static %}
{% block title %}make payment {% endblock %}

{% block content %}

<script src="https://js.paystack.co/v1/inline.js"></script>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
<!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
<!-- ======= Breadcrumbs ======= -->
<main id="main">
<!-- ======= Breadcrumbs ======= -->
<div class="breadcrumbs">
	<div class="page-header d-flex align-items-center" style="background-image: url('assets/img/page-header.jpg');">
	  <div class="container position-relative">
		<div class="row d-flex justify-content-center">
		  <div class="col-lg-6 text-center">
			<h2>Complete Payment</h2>
		  </div>
		</div>
	  </div>
	</div>
	<nav>
	  <div class="container">
		<ol>
		  <li><a href="{% url 'landing_page' %}">Home</a></li>
		</ol>
	  </div>
	</nav>
  </div><!-- End Breadcrumbs -->
<section class="features-1">
	<div class="container">
		<div class="row">
		<div class="col-12 col-lg-12" data-aos="fade-up" data-aos-delay="300">
			<div class="box-feature">
			</div>
			<div class="col-lg-7">
				{% if messages %}
					{% for message in messages %}
					  <div class="alert alert-warning alert-dismissible fade show" role="alert">
						{{ message }}
						<button  type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
					  </div>
	
	
					{% endfor %}
				  {% endif %}
				<div class="row gy-4">
				  <h4> You are about to Pay ksh. {{ payment.amount }} to {% for infor in companyinfor %} {{infor.company_name}} {% endfor %}</h4>
				</div>
				<button id="complete-purchase-button"  onclick="payWithPaystack()" class="btn btn-primary btn-block mb-4">Complete Purchase</button>
			</div><!-- End Quote Form -->
		</div>
		</div>
	</div>
</section>


</main>

<script>
	function payWithPaystack() {

		let currency = "KES";
		let plan = "";
		let ref = "{{ payment.ref }}";
		let amount = "{{ payment.amount }}";
		let obj = {
			key: "{{ paystack_pub_key }}",
			email: "{{ payment.email }}",
			amount: "{{ amount_value }}",
			ref: ref,
			callback: function (response) {
				window.location.href = "{% url 'verify_payment' payment.ref %}";
			},
		};
		if (Boolean(currency)) {
			obj.currency = currency.toUpperCase();
		}
		if (Boolean(plan)) {
			obj.plan - plan;
		}

		var handler = PaystackPop.setup(obj);
		handler.openIframe();
	}
</script>


{% endblock %}

templates/search.html
{%extends "blog-main.html" %}
{% load static %}

{% block title%} Blog Search {%endblock title%}
{%block content %}

  <main id="main" >

    <!-- ======= Breadcrumbs ======= -->
    <section class="breadcrumbs">
      <div class="container mt-2">

        <ol>
          <li><a href="{% url 'blog' %}">Blog</a></li>
        </ol>
        <h2>Search Results</h2>

      </div>
    </section><!-- End Breadcrumbs -->

    <!-- ======= Blog Section ======= -->
    <section id="blog" class="blog">
      <div class="container" data-aos="fade-up">

        <div class="row">
            
          <div class="col-lg-4">


            <div class="sidebar">

              <h3 class="sidebar-title">Search</h3>
              <div class="sidebar-item search-form">
                <form action="{% url 'search' %}">
                  <input type="text" name="query" placeholder="search">
                  <button type="submit"><i class="bi bi-search"></i></button>
                </form>
              </div><!-- End sidebar search formn-->

              <h3 class="sidebar-title"><i class="bi bi-folder"></i> Categories</h3>
              <div class="sidebar-item categories">
                <ul>
                  {%for category in categories %}
                  <li id = "category"><a href="{% url 'search' %}?query={{ query }}&category={{category.id}}">{{category.name}} <span>({{category.blog_set.count}})</span></a></li>
                  {%endfor%}
                </ul>
              </div><!-- End sidebar categories-->

              <h3 class="sidebar-title"><i class="bi bi-tags"></i> Tags</h3>
              <div class="sidebar-item tags">
                <ul>
                  {%for tag in tags %}
                  <li><a href="{% url 'search' %}?query={{ query }}&tag={{tag.id}}">{{tag.name}}</a></li>
                  {% endfor %}
                  
                </ul>
              </div><!-- End sidebar tags-->

            </div><!-- End sidebar -->

          </div><!-- End blog sidebar -->

          <div class="col-lg-8 entries">
            {%if blogs %}
            {%for blog in blogs %}
            <article class="entry">

              <div class="entry-img">
                {% if blog.thumbnail %}
                <img src="{{blog.imageURL}}" class="img-fluid" alt="">
                {% else %}
                <img src="{% static 'assets/img/blog-' %}{{blog.id}}.jpg" style="width: 100%;" class="img-fluid" alt=""/>
                {% endif %}
              </div>

              <h2 class="entry-title">
                <a href="{% url 'blog_single' blog.slug %}">{{blog.title}}</a>
              </h2>

              <div class="entry-meta">
                <ul>
                  <li class="d-flex align-items-center"><i class="bi bi-person"></i> {{blog.author}}</li>
                  <li class="d-flex align-items-center"><i class="bi bi-clock"></i><time datetime="2020-01-01">{{blog.dateUpdated |date}}</time></li>
                  <li class="d-flex align-items-center"><i class="bi bi-chat-dots"></i> {{blog.comment_set.count}} Comments</li>
                </ul>
              </div>

              <div class="entry-content">
                <p>{{blog.content|truncatechars:455 |safe}}</p>
                <div class="entry-footer">
                    <i class="bi bi-folder"></i>
                    <ul class="cats">
                      
                      <li><a href="{% url 'search' %}?query={{ query }}&category={{category.id}}">{{blog.categories.name}}</a></li>
                      
                    </ul>
    
                    <i class="bi bi-tags"></i>
                    <ul class="tags">
                      
                      <li><a href="#">tag</a></li>
                      
                    </ul>
                  </div>
                <div class="read-more">
                  <a href="{% url 'blog_single' blog.slug %}">Read More</a>
                </div>
              </div>

            </article><!-- End blog entry -->
            {%endfor%}

            <!-- paginator
            <div class="row">
              <div class="col-md-12 ">
                {% if blogs.has_other_pages %}
                  <ul class="pagination justify-content-center blog-pagination">
                    {% if blogs.has_previous %}
                      <a href="?page={{blogs.previous_page_number}}" class="page-link">&laquo;</a>
                    {% else %}
                      <li class="page-item disabled">
                        <a class="page-link">&laquo;</a>
                      </li>
                    {% endif %}
                    {% for i in blogs.paginator.page_range %}
                      {% if blogs.number == i %}
                        <li class="page-item active">
                          <a class="page-link">{{ i }}</a>
                        </li>
                      {% else %}
                        <li class="page-item">
                          <a href="?page={{i}}" class="page-link">{{ i }}</a>
                        </li>
                      {% endif %}
                    {% endfor %}
                    {% if blogs.has_next %}
                      <a href="?page={{ blogs.next_page_number }}" class="page-link">&raquo;</a>
                    {% else %}
                      <li class="page-item disabled">
                        <a class="page-link">&raquo;</a>
                      </li>
                    {% endif %}
                  </ul>
                {% endif %}
              </div>
            </div> -->
            {%else%}
            <div class="col-8 justify-content-center">
                <h6>No Match Results !!!</h6>
            </div>
            {%endif%}

          </div><!-- End blog entries list -->

        </div>

      </div>
    </section><!-- End Blog Section -->

  </main><!-- End #main -->

  {% endblock %}
  

templates/testimonial.html
{% load static %}
<!-- ======= Testimonials Section ======= -->
{% if testimonials %}
<section id="testimonials" class="testimonials">
    <h3 class="text-center" style="font-size: 20px; font-weight: bold; color: #fff; ">World Class Entrepreneurs Love Using SalesGenie AI</h3>

    <div class="container">
      <div class="slides-1 swiper">
        <div class="swiper-wrapper">
          {% for testimony in testimonials %}
          <div class="swiper-slide">
            <div class="testimonial-item">
              {% if testimony.imageURL %}
              <img src="{{testimony.imageURL}}" class="testimonial-img" alt="">
              {% else %}
              <img src="{% static 'assets/img/profile.png' %}" class="testimonial-img" alt="">
              <h3>{{testimony.testimonial_name}}</h3>
              {% endif %}
              <h4>{{testimony.testimonial_proffession}}</h4>
              <div class="stars">
                <i class="bi bi-star-fill"></i><i class="bi bi-star-fill"></i><i class="bi bi-star-fill"></i><i class="bi bi-star-fill"></i><i class="bi bi-star-fill"></i>
              </div>
              <p>
                <i class="bi bi-quote quote-icon-left"></i>
                {{testimony.testimonial_message}}
                <i class="bi bi-quote quote-icon-right"></i>
              </p>
            </div>
          </div><!-- End testimonial item -->
          {%endfor %}
        </div>
        <div class="swiper-pagination"></div>
      </div>

    </div>
</section><!-- End Testimonials Section -->
{% endif %}